url:         https://adrien.is
info:
  # Root URL where the site will be published
  url:         https://adrien.is

  # Blog Information
  title:        'Adrien Lemaire blogs'
  author:         'Adrien Lemaire'
  subtitle:     'about Productivity, Efficiency and Education'
  cover_image:  blog-cover.jpg
  about_image:  blog-cover.jpg
  logo:         logo.png
  avatar:       al.jpg
  bio:          Full-stack Engineer
  
  # Company information
  #company:      Incorporated
  #company_url:  http://sendtoinc.com/
  facebook:     fandekasp
  twitter:      Fandekasp
  github:       Fandekasp
  gplus:        'AdrienLemaire'
  linkedin:     adrienlemaire
  about_link:   https://adrien.is/about
  
  # Product Information
  #product_link: http://incorporated.sendtoinc.com/
  #tagline:      'Get a modern blog for your company'
  
  # Comments
  disqus:
    # Eg. 'exampleblog' Set to false to disable comments
    shortname:  false
  
  # Sharing settings
  sharing:
    twitter:   true 
    facebook:  true 
    gplus:     true 
    hn:        true 
    
  # Google Fonts
  # eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
  google_font: 'Droid+Sans:400,700'

  google_site_verification: 'google9960cac966e28c0a.html'
  
  # Setup your fonts, colors etc at _assets/stylesheets/main.scss

relative_permalinks:  true
paginate:             10
excerpt_separator:    '<!-- more -->'

# safe mode must be disabled to use jekyll-assets.
safe:               false

#
# jekyll-assets: see more at https://github.com/ixti/jekyll-assets
#
assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
  js_compressor: uglifier
  css_compressor: sass
  cachebust: none
  cache: false
  gzip: [ text/css, application/javascript ]
  debug: false


excerpt_separator: <!--more-->
permalink: /:title

gems:
  - jekyll-sitemap
