# Site settings
title: Adrien Lemaire
email: lemaire.adrien@gmail.com

description: > # this means to ignore newlines until "baseurl:"
  Software Engineer, Product maker, Productivity Hacker.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fandekasp.github.io" # the base hostname & protocol for your site
twitter_username: Fandekasp
github_username:  Fandekasp
linkedin_username:  adrienlemaire

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: default    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown

# Pagination
paginate: 3
